### ISSUE TITLE
Team entries should contain username

### ISSUE THREAD

**Issue by Istar-Eldritch** [repositive/repositive-content#4]
The mappers should create an object from the content in order to inject it's variables in the templates. Not add new entries to the content. The username is not part of the content and it's computed based on the file name.
https://github.com/repositive/repositive-static/blob/master/gulpfile.js#L63-L67

The username should be added to the team entries so we can avoid adding content in the template assembler.

https://github.com/repositive/repositive-content/blob/master/team/adrian.json
This entry for adrian should be: 
```json
{
  "name":"Adrian Alexa",
  "title":"Co-founder and CTO",
  "username": "adrian",
  "bio":"Adrian is a data scientist with expertise in algorithm optimisation and API development. While working at Illumina, Adrian built APIs for Illumina’s BaseSpace environment and tools for extracting statistics out of large genomic datasets. Prior to that he worked as a research associate at Max Planck Institute for Informatics, Germany.",
  "social": {
    "twitter":"_aalexa_",
    "linkedin":"aalexa"
  }
}
```

**Comment by tombyers** [comment]
Username key has now been added to each user.json

**Comment by Istar-Eldritch** [comment]
👍
